version: '3'
services:
  influxdb:
    image: influxdb:2.1-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE:     ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG:      ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET:   ${INFLUXDB_INIT_BUCKET}
