version: "3"
services:
  influxdb:
    image: influxdb:2.1-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE:        ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME:    ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD:    ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG:         ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET:      ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}

  grafana:
    image: grafana/grafana:8.5.1
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER:     ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:
